### ISSUE TITLE
Crash on Thermos

### ISSUE THREAD

**Issue by bangbang93** [ternsip/Placemod#2]
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 16-6-16 下午9:55
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_77617_a(I)Lnet/minecraft/util/IIcon;
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_77617_a(I)Lnet/minecraft/util/IIcon;
        at com.ternsip.placemod.Decorator.bindHooks(Decorator.java:258)
        at com.ternsip.placemod.Decorator.<clinit>(Decorator.java:576)
        at com.ternsip.placemod.Placemod.init(Placemod.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
        ... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Thermos Version: Linux (amd64) version 2.6.32-431.el6.x86_64
        Plugins: 1.8.0_60, Oracle Corporation
        Disabled Plugins: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Operating System: 5878827536 bytes (5606 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
        Java Version: 11 total; -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms6G -Xmx6G -XX:hashCode=5
        Java VM Version: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Memory: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        JVM Flags: 11 total; -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms6G -Xmx6G -XX:hashCode=5
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 49 mods loaded, 49 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHI    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
        UCHI    FML{7.10.99.99} [Forge Mod Loader] (Thermos-1.7.10-1558-57-server.jar) 
        UCHI    Forge{10.13.4.1614} [Minecraft Forge] (Thermos-1.7.10-1558-57-server.jar) 
        UCHI    kimagine{0.2} [KImagine] (minecraft.jar) 
        UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
        UCHI    InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
        UCHI    NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
        UCHI    PotionExtensionCore{1.0.4-forMC1.7} [PotionExtensionCore] (minecraft.jar) 
        UCHI    modJ_StarMinerCore{0.9.8} [StarMinerCore] (minecraft.jar) 
        UCHI    <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
        UCHI    debug{1.0} [debug] (denseores-1.6.2.jar) 
        UCHI    betterorefortune{1.0.1} [Better Ore Fortune] (1.7.10 更好的矿物掉落Mod[心殇汉化]-V1.0.1.jar) 
        UCHI    etfuturum{1.5.5} [Et Futurum] ([1.7.10]Et Futurum-1.5.5.jar) 
        UCHI    flashlight{ï¿½{version}} [Flashlight Mod] ([1.7.10]Flashlight-1.0.jar) 
        UCHI    More Fuel Mod{1.0.0} [More Fuel Mod] ([1.7.10]More Fuel-1.0.0.jar) 
        UCHI    AutoSapling{1.0} [AutoSapling] ([1.7.10]自动树苗种植——Auto Sapling-V1.1.jar) 
        UCHI    BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1237-universal.jar) 
        UCHI    ChestTransporter{2.0.3} [Chest Transporter] (ChestTransporter-2.0.3-MC1.7.10.jar) 
        UCHI    creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar) 
        UCHI    customnpcs{1.7.10b} [CustomNpcs] (customnpcs.jar) 
        UCHI    Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
        UCHI    DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V14c.jar) 
        UCHI    dsurround{1.0.5.6} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.5.6.jar) 
        UCHI    Dynmap{2.1-104} [Dynmap] (Dynmap-2.1-forge-1.7.10.jar) 
        UCHI    logicaldrops{0.9.4} [Logical Drops] (EM3R50N-LogicalDrops.1.7.10-0.9.4.jar) 
        UCHI    fc-dummy{0} [fc-dummy] (fastcraft-1.23.jar) 
        UCHI    FireGayForge{1.0} [FireGayForge] (FireGayForge-1.0.jar) 
        UCHI    GollumCoreLib{2.0.0} [Gollum Core Lib] (GollumCoreLib-2.0.0-1.7.10.jar) 
        UCHI    GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
        UCHI    HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
        UCHI    inventorytweaks{1.59-dev-155-5dbbb14} [Inventory Tweaks] (InventoryTweaks 物品整理 v1.59-155.jar) 
        UCHI    IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
        UCHI    reaper_lantern{1.47} [Lantern mod] (Lantern1.47[1.7.10].jar) 
        UCHI    NEIAddons{1.12.2.9} [NEI Addons] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHI    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHI    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHI    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHI    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHI    NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] (NEIPlugins NEI插件 v1.1.0.11.jar) 
        UCHI    opframe{0.1} [OnlinePictureFrame] (OnlinePicFrame v1.0 mc1.7.10.zip) 
        UCHE    placemod{3.4} [Placemod] (placemod-3.4-1.7.X.jar) 
        UCHI    RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V14c.jar) 
        UCHI    redgear_core{2.1.3} [Red Gear Core] (RedGearCore-1.7.10-2.1.3.jar) 
        UCHI    redgear_snowfall{2.2.2} [Snowfall] (Snowfall-1.7.10-2.2.2 .jar) 
        UCHI    modJ_StarMiner{0.9.8bf1} [Starminer Mod] (Starminer1710-0.9.8bf1.jar) 
        UCHI    stefinusguns{0.5.2} [New Stefinus Guns] (Stefinus Guns-0.5.2 TZ.jar) 
        UCHI    StorageDrawers{1.7.10-1.9.4} [Storage Drawers] (StorageDrawers-1.7.10-1.9.4.jar) 
        UCHI    EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (轻松合成台-1.7.10-2.0.1.16牛奶汉化.jar) 
        UCHI    denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
        Profiler Position: N/A (disabled)
        Player Count: 0 / 93; []
        Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
        Type: Dedicated Server (map_server.txt)

```
I had try to use Thermos-1.7.10-1558-57-server.jar and Thermos-1.7.10-1614-46-server.jar,same to crash.
On client Forge 1558, it works properly

**Comment by ternsip** [comment]
Fixed in 1.7.X - 3.5
download: https://github.com/ternsip/Placemod/raw/master/1.7.X/builds/placemod-3.5-1.7.X.jar

**Comment by ternsip** [comment]
Is it works?

**Comment by bangbang93** [comment]
It works
But i just got another crash
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 6/18/16 5:26 PM
Description: Exception getting block type in world

java.lang.IllegalArgumentException
        at net.minecraft.util.WeightedRandom.func_76269_a(WeightedRandom.java:82)
        at net.minecraft.util.WeightedRandom.func_76274_a(WeightedRandom.java:113)
        at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:37)
        at com.ternsip.placemod.Structure.paste(Structure.java:241)
        at com.ternsip.placemod.Decorator.place(Decorator.java:225)
        at com.ternsip.placemod.Decorator.generate(Decorator.java:173)
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:472)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1201)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
        at net.minecraft.world.World.func_72964_e(World.java:799)
        at net.minecraft.world.World.func_147439_a(World.java:702)
        at net.minecraft.world.World.func_147437_c(World.java:722)
        at net.minecraft.block.BlockStaticLiquid.func_149674_a(BlockStaticLiquid.java:95)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:568)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at net.minecraft.util.WeightedRandom.func_76269_a(WeightedRandom.java:82)
        at net.minecraft.util.WeightedRandom.func_76274_a(WeightedRandom.java:113)
        at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:37)
        at com.ternsip.placemod.Structure.paste(Structure.java:241)
        at com.ternsip.placemod.Decorator.place(Decorator.java:225)
        at com.ternsip.placemod.Decorator.generate(Decorator.java:173)
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:472)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1201)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
        at net.minecraft.world.World.func_72964_e(World.java:799)

-- Requested block coordinates --
Details:
        Found chunk: true
        Location: World: (-833,4,288), Chunk: (at 15,0,0 in -53,18; contains blocks -848,0,288 to -833,255,303), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
Stacktrace:
        at net.minecraft.world.World.func_147439_a(World.java:702)
        at net.minecraft.world.World.func_147437_c(World.java:722)
        at net.minecraft.block.BlockStaticLiquid.func_149674_a(BlockStaticLiquid.java:95)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:568)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)

-- Affected level --
Details:
        Level name: world
        All players: 1 total; [EntityPlayerMP['Mollysuh'/4649, l='world', x=-825.37, y=91.83, z=96.47](Mollysuh at -825.366076441684,91.82812179467541,96.46519904815047)]
        Chunk stats: ServerChunkCache: 900 Drop: 0
        Level seed: 93939
        Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
        Level generator options: 
        Level spawn location: World: (1187,63,-392), Chunk: (at 3,3,8 in 74,-25; contains blocks 1184,0,-400 to 1199,255,-385), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
        Level time: 943546 game time, 1303748 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 44170 (now: false), thunder time: 4347 (now: true)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
        at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Thermos Version: cyberdynecc:Thermos:1.7.10-1614.57
        Plugins: EasyFreeze, DragonFly, WorldEdit, Essentials, GroupManager, PluginManager, PvPToggle, ProtocolLib, WorldGuard, Multiverse-Core, 2dmmcService, EssentialsProtect, Stargate, EssentialsGeoIP, EssentialsChat, automessage, BanItem, EssentialsAntiBuild, AT, mcMMO, Vault, EssentialsSpawn, Prism, FireGay, dynmap, Dynmap-Essentials, WorldBorder, LWC, Dynmap-WorldGuard, SignShop, Residence, Shop
        Disabled Plugins: 
        Operating System: Linux (amd64) version 2.6.32-431.el6.x86_64
        Java Version: 1.8.0_60, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 4360986104 bytes (4158 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
        JVM Flags: 11 total; -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms6G -Xmx6G -XX:hashCode=5
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 9, tallocated: 91
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 42 mods loaded, 42 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
        UCHIJAAAA       FML{7.10.99.99} [Forge Mod Loader] (Thermos-1.7.10-1614-57-server.jar) 
        UCHIJAAAA       Forge{10.13.4.1614} [Minecraft Forge] (Thermos-1.7.10-1614-57-server.jar) 
        UCHIJAAAA       kimagine{0.2} [KImagine] (minecraft.jar) 
        UCHIJAAAA       CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
        UCHIJAAAA       NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
        UCHIJAAAA       PotionExtensionCore{1.0.4-forMC1.7} [PotionExtensionCore] (minecraft.jar) 
        UCHIJAAAA       debug{1.0} [debug] (denseores-1.6.2.jar) 
        UCHIJAAAA       betterorefortune{1.0.1} [Better Ore Fortune] (1.7.10 更好的矿物掉落Mod[心殇汉化]-V1.0.1.jar) 
        UCHIJAAAA       flashlight{ï¿½{version}} [Flashlight Mod] ([1.7.10]Flashlight-1.0.jar) 
        UCHIJAAAA       More Fuel Mod{1.0.0} [More Fuel Mod] ([1.7.10]More Fuel-1.0.0.jar) 
        UCHIJAAAA       AutoSapling{1.0} [AutoSapling] ([1.7.10]自动树苗种植——Auto Sapling-V1.1.jar) 
        UCHIJAAAA       BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
        UCHIJAAAA       ChestTransporter{2.0.3} [Chest Transporter] (ChestTransporter-2.0.3-MC1.7.10.jar) 
        UCHIJAAAA       creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar) 
        UCHIJAAAA       customnpcs{1.7.10b} [CustomNpcs] (customnpcs.jar) 
        UCHIJAAAA       dsurround{1.0.5.6} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.5.6.jar) 
        UCHIJAAAA       Dynmap{2.1-104} [Dynmap] (Dynmap-2.1-forge-1.7.10.jar) 
        UCHIJAAAA       FireGayForge{1.0} [FireGayForge] (FireGayForge-1.0.jar) 
        UCHIJAAAA       GollumCoreLib{2.0.0} [Gollum Core Lib] (GollumCoreLib-2.0.0-1.7.10.jar) 
        UCHIJAAAA       GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
        UCHIJAAAA       HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
        UCHIJAAAA       inventorytweaks{1.59-dev-155-5dbbb14} [Inventory Tweaks] (InventoryTweaks 物品整理 v1.59-155.jar) 
        UCHIJAAAA       IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
        UCHIJAAAA       reaper_lantern{1.47} [Lantern mod] (Lantern1.47[1.7.10].jar) 
        UCHIJAAAA       mcheli{0.10.9} [MC Helicopter] (mcheli) 
        UCHIJAAAA       NEIAddons{1.12.2.9} [NEI Addons] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHIJAAAA       NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHIJAAAA       NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHIJAAAA       NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHIJAAAA       NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons NEI扩展 v1.12.2.9.jar) 
        UCHIJAAAA       NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] (NEIPlugins NEI插件 v1.1.0.11.jar) 
        UCHIJAAAA       opframe{0.1} [OnlinePictureFrame] (OnlinePicFrame v1.0 mc1.7.10.zip) 
        UCHIJAAAA       placemod{3.5} [Placemod] (placemod-3.5-1.7.X.jar) 
        UCHIJAAAA       redgear_core{2.1.3} [Red Gear Core] (RedGearCore-1.7.10-2.1.3.jar) 
        UCHIJAAAA       redgear_snowfall{2.2.2} [Snowfall] (Snowfall-1.7.10-2.2.2 .jar) 
        UCHIJAAAA       stefinusguns{0.5.2} [New Stefinus Guns] (Stefinus Guns-0.5.2 TZ.jar) 
        UCHIJAAAA       StorageDrawers{1.7.10-1.9.4} [Storage Drawers] (StorageDrawers-1.7.10-1.9.4.jar) 
        UCHIJAAAA       Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
        UCHIJAAAA       EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (轻松合成台-1.7.10-2.0.1.16牛奶汉化.jar) 
        UCHIJAAAA       mfs{2.0.1} [Minecraft Flight Simulator] (飞机MOD.jar) 
        UCHIJAAAA       denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 1 / 93; [EntityPlayerMP['Mollysuh'/4649, l='world', x=-825.37, y=91.83, z=96.47](Mollysuh at -825.366076441684,91.82812179467541,96.46519904815047)]
        Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
        Type: Dedicated Server (map_server.txt)
```

Seems something happened while generate random chest.

By the way,is there any settings to control random item in chest?I would ban some creative-mode-only items from random
